services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "leo-vegas-db"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "test"
      # You can use whatever password you like
      MYSQL_PASSWORD: "test"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "pass"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - leo-vegas-db:/var/lib/mysql

# Names our volume
volumes:
  leo-vegas-db:
